server:
  port: 8802

eureka:
  client:
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-expiration-duration-in-seconds: 5 #如果超过5秒
    lease-renewal-interval-in-seconds: 2 #心跳间隔时间
    instance-id: receive-8802.com
    prefer-ip-address: true

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        input:
          destination: studyExchange #rabbitMQ的Exchange名称
          content-type: application/json
          binder: defaultRabbit
          group: atguiguA

management:
  endpoints:
    web:
      exposure:
        include: "*"