server:
  port: 80

#spring:
 # application:
  #  name: cloud-order-service

eureka:
  client:
    #表示自己是否向注册中心注册自己 默认是true
    register-with-eureka: false
    #是否从eurekaServer抓取已有的注册信息，默认为TRUE。单节点无所谓，集群必须为TRUE才可以配合ribbon使用负载均衡
    #fetchRegistry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都要依赖这个地址
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版

ribbon:

  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug
